### ISSUE TITLE
方案讨论

### ISSUE THREAD

**Issue by chejdj** [HuolalaTech/HLLOfflineWebView-android#5]
我看这边实现方案是 修改loadUrl从远端修改为本地file:/// 协议从而实现本地资源加载。
这个可能带来跨端问题，而且资源粒度太大，整个页面。
想请问一下考虑过
在WebViewClient
` WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request)` 中进行拦截，这样可以更小粒度缓存一些公共资源和项目资源等。 比如某个css,图片是多个HTML页面公用的

**Comment by shiqos** [comment]
> 我看这边实现方案是 修改loadUrl从远端修改为本地file:/// 协议从而实现本地资源加载。 这个可能带来跨端问题，而且资源粒度太大，整个页面。 想请问一下考虑过 在WebViewClient ` WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request)` 中进行拦截，这样可以更小粒度缓存一些公共资源和项目资源等。 比如某个css,图片是多个HTML页面公用的

非货拉拉开发回答, 这种方案是可行的, 实际上大多数也是这么干的

**Comment by KelvinKzz** [comment]
您好，是的，我们也有粒度更小的离线方案，适用范围不同。
